# Generated by Django 4.1.1 on 2022-12-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='brand',
            new_name='Product_brand',
        ),
    ]
