# Generated by Django 4.1.1 on 2022-12-27 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='src.product_brand'),
        ),
    ]
