# Generated by Django 4.1.1 on 2022-12-27 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, default='2', null=True, on_delete=django.db.models.deletion.CASCADE, to='src.product_brand'),
        ),
    ]
