export const SALES_LIST_FAIL = "SALES_LIST_FAIL";
export const SALES_LIST_REQUEST = "SALES_LIST_REQUEST";
export const SALES_LIST_SUCCESS = "SALES_LIST_SUCCESS";

export const SALES_ADD_LIST_FAIL = "SALES_ADD_LIST_FAIL";
export const SALES_ADD_LIST_REQUEST = "SALES_ADD_LIST_REQUEST";
export const SALES_ADD_LIST_SUCCESS = "SALES_ADD_LIST_SUCCESS";