export const STORE_LIST_FAIL="STORE_LIST_FAIL"
export const STORE_LIST_REQUEST="STORE_LIST_REQUEST"
export const STORE_LIST_SUCCESS="STORE_LIST_SUCCESS"


export const STORE_DETAILS_FAIL="STORE_DETAILS_FAIL"
export const STORE_DETAILS_REQUEST="STORE_DETAILS_REQUEST"
export const STORE_DETAILS_SUCCESS="STORE_DETAILS_SUCCESS"

export const STORE_OWNER_LIST_FAIL="STORE_OWNER_LIST_FAIL"
export const STORE_OWNER_LIST_REQUEST="STORE_OWNER_LIST_REQUEST"
export const STORE_OWNER_LIST_SUCCESS="STORE_OWNER_LIST_SUCCESS"


